language: php
php:
- 7.0
sudo: false
env:
  global:
  - SIMPLETEST_DB=sqlite://tmp/site.sqlite
  - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
  - RELEASE=stable COMPOSER_CHANNEL=stable
before_script:
  - psql -c 'create database divelog;' -U postgres
before_install:
  - openssl aes-256-cbc -K $encrypted_66644bb89341_key -iv $encrypted_66644bb89341_iv -in id_rsa.enc -out id_rsa -d
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
install:
  - composer --verbose install
script:
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.1.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  - ./../vendor/bin/phpunit -v -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache
  - ./../vendor/bin/drush
  - ./../vendor/bin/drupal
